"""initial schema

Revision ID: 273aefd6e9e8
Revises: 
Create Date: 2026-08-24 17:03:39.052307+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '273aefd6e9e8'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

APPEND_ONLY_TABLES = (
    "audit_events",
    "order_transitions",
    "stamp_events",
    "ledger_entries",
    "journals",
    "payment_receipts",
    "verifications",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_principal_id', sa.UUID(), nullable=True),
    sa.Column('actor_subject', sa.String(length=128), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("outcome IN ('success', 'failure', 'denied')", name=op.f('ck_audit_events_outcome_valid')),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_events_event_id')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_events_hash'))
    )
    op.create_index('ix_audit_events_actor', 'audit_events', ['actor_subject', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_target', 'audit_events', ['target_type', 'target_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tin', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kyb_status', sa.String(length=32), nullable=False),
    sa.Column('kyb_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kyb_status IN ('unverified', 'verified', 'suspended')", name=op.f('ck_companies_kyb_status_valid')),
    sa.CheckConstraint("risk_tier IN ('low', 'medium', 'high')", name=op.f('ck_companies_risk_tier_valid')),
    sa.CheckConstraint('char_length(tin) >= 8', name=op.f('ck_companies_tin_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('tin', name=op.f('uq_companies_tin'))
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbox_messages_dedupe_key'))
    )
    op.create_index(op.f('ix_outbox_messages_created_at'), 'outbox_messages', ['created_at'], unique=False)
    op.create_index('ix_outbox_pending', 'outbox_messages', ['available_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('clean', 'findings', 'error')", name=op.f('ck_reconciliation_runs_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_runs'))
    )
    op.create_index(op.f('ix_reconciliation_runs_started_at'), 'reconciliation_runs', ['started_at'], unique=False)
    op.create_table('serial_counters',
    sa.Column('product_category', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('next_value >= 1', name=op.f('ck_serial_counters_next_value_positive')),
    sa.PrimaryKeyConstraint('product_category', 'year', name=op.f('pk_serial_counters'))
    )
    op.create_table('tariffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(length=64), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_bps', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statutory_reference', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_tariffs_effective_range')),
    sa.CheckConstraint('unit_price_minor > 0', name=op.f('ck_tariffs_unit_price_positive')),
    sa.CheckConstraint('vat_bps >= 0 AND vat_bps <= 10000', name=op.f('ck_tariffs_vat_bps_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs'))
    )
    op.create_index('ix_tariffs_category_current', 'tariffs', ['product_category', 'effective_from'], unique=True)
    op.create_index(op.f('ix_tariffs_created_at'), 'tariffs', ['created_at'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role IN ('requester') AND company_id IS NOT NULL) OR role NOT IN ('requester')", name=op.f('ck_principals_requester_requires_company')),
    sa.CheckConstraint("role IN ('requester', 'analyst', 'supervisor', 'treasury', 'operator', 'auditor', 'admin', 'device')", name=op.f('ck_principals_role_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_principals_company_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_principals')),
    sa.UniqueConstraint('subject', name=op.f('uq_principals_subject'))
    )
    op.create_index(op.f('ix_principals_created_at'), 'principals', ['created_at'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], name=op.f('fk_credentials_principal_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_credentials_token_hash'))
    )
    op.create_index(op.f('ix_credentials_created_at'), 'credentials', ['created_at'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('in_progress', 'completed')", name=op.f('ck_idempotency_records_state_valid')),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], name=op.f('fk_idempotency_records_principal_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('scope', 'idempotency_key', name='uq_idempotency_records_scope_key')
    )
    op.create_index(op.f('ix_idempotency_records_created_at'), 'idempotency_records', ['created_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_ref', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_bps', sa.Integer(), nullable=False),
    sa.Column('vat_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('delivery_state', sa.String(length=64), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('compliance_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("risk_tier IN ('low', 'medium', 'high')", name=op.f('ck_orders_risk_tier_valid')),
    sa.CheckConstraint("status IN ('submitted', 'compliance_pending', 'compliance_rejected', 'awaiting_approval', 'approved', 'rejected', 'awaiting_payment', 'paid', 'issuing', 'issued', 'cancelled')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('subtotal_minor = unit_price_minor * quantity', name=op.f('ck_orders_subtotal_matches_quantity')),
    sa.CheckConstraint('subtotal_minor > 0', name=op.f('ck_orders_subtotal_positive')),
    sa.CheckConstraint('total_minor = subtotal_minor + vat_minor', name=op.f('ck_orders_total_matches_components')),
    sa.CheckConstraint('unit_price_minor > 0', name=op.f('ck_orders_unit_price_positive')),
    sa.CheckConstraint('vat_minor >= 0', name=op.f('ck_orders_vat_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_orders_company_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['principals.id'], name=op.f('fk_orders_submitted_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_orders_tariff_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_ref', name=op.f('uq_orders_order_ref'))
    )
    op.create_index('ix_orders_company_status', 'orders', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('actor_principal_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name=op.f('ck_approvals_decision_valid')),
    sa.CheckConstraint("level IN ('analyst', 'supervisor')", name=op.f('ck_approvals_level_valid')),
    sa.ForeignKeyConstraint(['actor_principal_id'], ['principals.id'], name=op.f('fk_approvals_actor_principal_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_approvals_order_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('order_id', 'level', name='uq_approvals_order_level')
    )
    op.create_index(op.f('ix_approvals_created_at'), 'approvals', ['created_at'], unique=False)
    op.create_table('order_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor_principal_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_principal_id'], ['principals.id'], name=op.f('fk_order_transitions_actor_principal_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_transitions_order_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_transitions'))
    )
    op.create_index(op.f('ix_order_transitions_created_at'), 'order_transitions', ['created_at'], unique=False)
    op.create_index('ix_order_transitions_order', 'order_transitions', ['order_id', 'created_at'], unique=False)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('awaiting_payment', 'settled', 'mismatched', 'cancelled')", name=op.f('ck_payment_intents_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payment_intents_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_intents_order_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_intents')),
    sa.UniqueConstraint('order_id', name=op.f('uq_payment_intents_order_id')),
    sa.UniqueConstraint('reference', name=op.f('uq_payment_intents_reference'))
    )
    op.create_index(op.f('ix_payment_intents_created_at'), 'payment_intents', ['created_at'], unique=False)
    op.create_table('stamp_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_count', sa.BigInteger(), nullable=False),
    sa.Column('issued_count', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'issuing', 'issued', 'inspection_failed')", name=op.f('ck_stamp_batches_status_valid')),
    sa.CheckConstraint('issued_count >= 0 AND issued_count <= requested_count', name=op.f('ck_stamp_batches_issued_within_requested')),
    sa.CheckConstraint('requested_count > 0', name=op.f('ck_stamp_batches_requested_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_stamp_batches_order_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stamp_batches')),
    sa.UniqueConstraint('order_id', name=op.f('uq_stamp_batches_order_id'))
    )
    op.create_index(op.f('ix_stamp_batches_created_at'), 'stamp_batches', ['created_at'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('lot_size', sa.BigInteger(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('accept_number', sa.Integer(), nullable=False),
    sa.Column('reject_number', sa.Integer(), nullable=False),
    sa.Column('defects_found', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('inspector_principal_id', sa.UUID(), nullable=False),
    sa.Column('defective_serials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('defects_found >= 0', name=op.f('ck_inspections_defects_non_negative')),
    sa.CheckConstraint('sample_size > 0 AND sample_size <= lot_size', name=op.f('ck_inspections_sample_within_lot')),
    sa.ForeignKeyConstraint(['batch_id'], ['stamp_batches.id'], name=op.f('fk_inspections_batch_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_principal_id'], ['principals.id'], name=op.f('fk_inspections_inspector_principal_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections')),
    sa.UniqueConstraint('batch_id', name='uq_inspections_batch_id')
    )
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_table('payment_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('declared_reference', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('matched', 'amount_mismatch', 'unknown_reference', 'duplicate')", name=op.f('ck_payment_receipts_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payment_receipts_amount_positive')),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], name=op.f('fk_payment_receipts_payment_intent_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_receipts')),
    sa.UniqueConstraint('external_reference', name=op.f('uq_payment_receipts_external_reference'))
    )
    op.create_index(op.f('ix_payment_receipts_ingested_at'), 'payment_receipts', ['ingested_at'], unique=False)
    op.create_table('stamps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('secure_code_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status <> 'active') OR (activated_at IS NOT NULL)", name=op.f('ck_stamps_active_requires_timestamp')),
    sa.CheckConstraint("(status <> 'void') OR (voided_at IS NOT NULL)", name=op.f('ck_stamps_void_requires_timestamp')),
    sa.CheckConstraint("status IN ('issued', 'active', 'void', 'expired')", name=op.f('ck_stamps_status_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['stamp_batches.id'], name=op.f('fk_stamps_batch_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stamps_company_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_stamps_order_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stamps')),
    sa.UniqueConstraint('serial', name=op.f('uq_stamps_serial'))
    )
    op.create_index('ix_stamps_batch', 'stamps', ['batch_id'], unique=False)
    op.create_index('ix_stamps_company_status', 'stamps', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_stamps_issued_at'), 'stamps', ['issued_at'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('payment_receipt_id', sa.UUID(), nullable=True),
    sa.Column('reverses_journal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_journals_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_receipt_id'], ['payment_receipts.id'], name=op.f('fk_journals_payment_receipt_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reverses_journal_id'], ['journals.id'], name=op.f('fk_journals_reverses_journal_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journals')),
    sa.UniqueConstraint('reference', name=op.f('uq_journals_reference')),
    sa.UniqueConstraint('reverses_journal_id', name=op.f('uq_journals_reverses_journal_id'))
    )
    op.create_index(op.f('ix_journals_created_at'), 'journals', ['created_at'], unique=False)
    op.create_table('stamp_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stamp_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_principal_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_principal_id'], ['principals.id'], name=op.f('fk_stamp_events_actor_principal_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], name=op.f('fk_stamp_events_stamp_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stamp_events'))
    )
    op.create_index(op.f('ix_stamp_events_created_at'), 'stamp_events', ['created_at'], unique=False)
    op.create_index('ix_stamp_events_stamp', 'stamp_events', ['stamp_id', 'created_at'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stamp_id', sa.UUID(), nullable=True),
    sa.Column('serial_presented', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('latitude_e7', sa.BigInteger(), nullable=True),
    sa.Column('longitude_e7', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('valid', 'unknown_serial', 'secure_code_mismatch', 'not_active', 'void', 'expired', 'velocity_suspect')", name=op.f('ck_verifications_outcome_valid')),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], name=op.f('fk_verifications_principal_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], name=op.f('fk_verifications_stamp_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    op.create_index(op.f('ix_verifications_occurred_at'), 'verifications', ['occurred_at'], unique=False)
    op.create_index('ix_verifications_serial', 'verifications', ['serial_presented', 'occurred_at'], unique=False)
    op.create_index('ix_verifications_stamp', 'verifications', ['stamp_id', 'occurred_at'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('debit', 'credit')", name=op.f('ck_ledger_entries_direction_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('fk_ledger_entries_journal_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_entries_account', 'ledger_entries', ['account', 'created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index('ix_ledger_entries_journal', 'ledger_entries', ['journal_id'], unique=False)

    op.execute(
        """
        CREATE OR REPLACE FUNCTION taxstamp_reject_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'table % is append-only; % is not permitted',
                TG_TABLE_NAME, TG_OP;
        END;
        $$;
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_no_update BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION taxstamp_reject_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION taxstamp_reject_mutation()"
        )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION taxstamp_assert_journal_balanced() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
            debits bigint;
            credits bigint;
            entry_count integer;
            currency_count integer;
            journal_currency char(3);
        BEGIN
            SELECT COALESCE(SUM(CASE WHEN direction = 'debit' THEN amount_minor ELSE 0 END), 0),
                   COALESCE(SUM(CASE WHEN direction = 'credit' THEN amount_minor ELSE 0 END), 0),
                   COUNT(*),
                   COUNT(DISTINCT currency)
              INTO debits, credits, entry_count, currency_count
              FROM ledger_entries
             WHERE journal_id = NEW.journal_id;
            IF entry_count < 2 THEN
                RAISE EXCEPTION 'journal % must have at least two entries', NEW.journal_id;
            END IF;
            IF currency_count <> 1 THEN
                RAISE EXCEPTION 'journal % mixes currencies', NEW.journal_id;
            END IF;
            SELECT currency INTO journal_currency FROM journals WHERE id = NEW.journal_id;
            IF journal_currency IS DISTINCT FROM NEW.currency THEN
                RAISE EXCEPTION 'entry currency % does not match journal %',
                    NEW.currency, NEW.journal_id;
            END IF;
            IF debits <> credits THEN
                RAISE EXCEPTION 'journal % is unbalanced: debits=% credits=%',
                    NEW.journal_id, debits, credits;
            END IF;
            RETURN NULL;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER ledger_entries_balanced
        AFTER INSERT ON ledger_entries
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION taxstamp_assert_journal_balanced()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS ledger_entries_balanced ON ledger_entries")
    op.execute("DROP FUNCTION IF EXISTS taxstamp_assert_journal_balanced()")
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete ON {table}")
    op.execute("DROP FUNCTION IF EXISTS taxstamp_reject_mutation()")
    op.drop_index('ix_ledger_entries_journal', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_verifications_stamp', table_name='verifications')
    op.drop_index('ix_verifications_serial', table_name='verifications')
    op.drop_index(op.f('ix_verifications_occurred_at'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index('ix_stamp_events_stamp', table_name='stamp_events')
    op.drop_index(op.f('ix_stamp_events_created_at'), table_name='stamp_events')
    op.drop_table('stamp_events')
    op.drop_index(op.f('ix_journals_created_at'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_stamps_issued_at'), table_name='stamps')
    op.drop_index('ix_stamps_company_status', table_name='stamps')
    op.drop_index('ix_stamps_batch', table_name='stamps')
    op.drop_table('stamps')
    op.drop_index(op.f('ix_payment_receipts_ingested_at'), table_name='payment_receipts')
    op.drop_table('payment_receipts')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_stamp_batches_created_at'), table_name='stamp_batches')
    op.drop_table('stamp_batches')
    op.drop_index(op.f('ix_payment_intents_created_at'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index('ix_order_transitions_order', table_name='order_transitions')
    op.drop_index(op.f('ix_order_transitions_created_at'), table_name='order_transitions')
    op.drop_table('order_transitions')
    op.drop_index(op.f('ix_approvals_created_at'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index('ix_orders_company_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_idempotency_records_created_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_credentials_created_at'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_principals_created_at'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_tariffs_created_at'), table_name='tariffs')
    op.drop_index('ix_tariffs_category_current', table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_table('serial_counters')
    op.drop_index(op.f('ix_reconciliation_runs_started_at'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_outbox_pending', table_name='outbox_messages', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_index(op.f('ix_outbox_messages_created_at'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_audit_events_target', table_name='audit_events')
    op.drop_index('ix_audit_events_actor', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
